-- Filter to logs generated by Kiwi Syslog generator
FILTER{ "syslog_http_request";
  enabled = false;
  source  = "syslog:udp://127.0.0.1";
  exclude = WHITE_IP;
  failregex = {
    "Test user connected to website http://([0-9.]-)/index.html";
  }
};
